branch-defaults:
  master:
    environment: delius-api-job-schedular-proto
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: delius-api-job-schedular-proto
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Docker running on
    64bit Amazon Linux/2.6.0
  default_region: eu-west-2
