version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV

      - checkout

      - setup_remote_docker

      - deploy:
          name: Build Derived Git Commit
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              GIT_REF=$CIRCLE_SHA1 BUILD_NUMBER=$CIRCLE_BUILD_NUM \
                npm run record-build-info
              git add --force --verbose build-info.json
              git config user.name "Circle CI"
              git config user.email "circle@circleci.com"
              git commit \
                -m "Deployment of build $CIRCLE_BUILD_NUM" \
                -m "$(git log --format=%B -n 1 $CIRCLE_SHA1)" \
                -m "From gitref $CIRCLE_SHA1"
            fi

      - deploy:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/publishDockerImage.sh delius-api-job-schedular "${BUILD_VERSION}" "${CIRCLE_BUILD_NUM}" "${CIRCLE_BUILD_URL}" "${CIRCLE_SHA1}" "${DOCKER_EMAIL}" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}"
            fi

      - deploy:
          name: Install elastic beanstalk CLI
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/installElasticbeanstalk.sh
            fi

      - deploy:
          name: Deploy to Elastic Beanstalk Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/deployElasticbeanstalk.sh delius-api-job-schedular "${BUILD_VERSION}"
            fi
