version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV

      - checkout

      - setup_remote_docker

      - deploy:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/publishDockerImage.sh delius-api-job-schedular "${BUILD_VERSION}" "${CIRCLE_BUILD_NUM}" "${CIRCLE_BUILD_URL}" "${CIRCLE_SHA1}" "${DOCKER_EMAIL}" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}"
            fi

      - deploy:
          name: Install elastic beanstalk CLI
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/installElasticbeanstalk.sh
            fi

      - deploy:
          name: Deploy to Elastic Beanstalk Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/deployElasticbeanstalk.sh delius-api-job-schedular "${BUILD_VERSION}"
            fi
